name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Echo
        uses: JoseThen/comment-pr@v1.2.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment: 'Hello! '

