name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Comment
        uses: GrantBirki/comment@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: "Hello from workf
