name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Echo
        run: echo 'KSKDKKD'

